name: Build & Push Microservices

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_REPO: xentey/hypersend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - user-auth

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend/services/${{ matrix.service }}
          file: ./backend/services/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ matrix.service }}-${{ env.SHORT_SHA }}
            ${{ env.DOCKER_REPO }}:${{ matrix.service }}-latest
